### ISSUE TITLE
Add a constant field with mapping in configuration

### ISSUE THREAD

**Issue by johnkrovitch** [larriereguichet/AdminBundle#76]
Add a way to display constant (such as "Published") based on configured mapping like : 

```yml
list:
    publicationStatus:
        type: constant
        options:
            mapping:
                0: lag.draft
                1: lag.published
...

```
